# Version 2023-03-05
name: Java CI
on: [push, pull_request]

jobs:
  build:
    uses: igniterealtime/openfire-plugin-builder-action/.github/workflows/openfire-plugin-build.yml@main
    secrets:
      IGNITE_REALTIME_MAVEN_USERNAME: ${{ secrets.IGNITE_REALTIME_MAVEN_USERNAME }}
      IGNITE_REALTIME_MAVEN_PASSWORD: ${{ secrets.IGNITE_REALTIME_MAVEN_PASSWORD }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout tests
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            test

      - name: Download the built plugin
        uses: actions/download-artifact@v4
        with:
          name: restAPI
          path: .

      - name: Rename plugin
        run: |
          mv restAPI-openfire-plugin-assembly.jar restAPI.jar
  
      - name: Run Openfire
        uses: igniterealtime/launch-openfire-action@v1.1.2
        with:
          version: 4.9.0
          config: ./test/demoboot-with-additions.xml
          plugin: ./restAPI.jar
      
      - uses: gacts/install-hurl@v1

      - name: Test the plugin
        run: |
          hurl --test --report-junit test-results.xml --variables-file test/test.env --jobs 1 test/*.hurl

      - name: Expose Openfire logs
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: Openfire server logs
          path: openfire/logs/*

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'test-results.xml'
          suite_regex: '*'
          include_passed: true
          detailed_summary: true
